---
name: 00 Container Actions Input Env

on:
  push:
    branches:
      - container-actions-input-env
  workflow_dispatch: 

jobs:
  bash-dockerfile:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: ./.github/actions/container-actions-input-env
        with:
          who-to-greet: "Passed env variable"
